### ISSUE TITLE
Issue with large family

### ISSUE THREAD

**Issue by Timothep** [rstacruz/kingraph#16]
Hi, I'm getting this error when working with a large family:

`kingraph genealogy.yml > genealogy.svg`

Error:
> add_segment: error
> add_segment: error
> add_segment: error
> add_segment: error
> add_segment: error
> add_segment: error
> add_segment: error
> failed at node 7167[0]
> Assertion failed: np->cells[0], at: maze.c,313,chkSgraph at Error
>     at jsStackTrace (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:5:20800)
>     at stackTrace (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:5:20983)
>     at ___assert_fail (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:5:603049)
>     at PU (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:17:39811)
>     at LU (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:17:34738)
>     at Array.HU (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:17:28119)
>     at Object.y5 [as dynCall_iii] (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:21:32521)
>     at invoke_iii (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:5:632212)
>     at yP (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:10:66616)
>     at Mf (C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:11:132553)

I raised the Memory for viz.js as suggested by @momack2 in [this other issue](https://github.com/rstacruz/kingraph/issues/6) but it doesn't seem to help. 

It seems to have to do with the family size among one house. This error occurs when it has more than 24 parent/children pairs.

Any idea what is going awry there?

**Comment by JetSetDoritos** [comment]
Solution from the linked issue that has worked for me

Edit C:\Users\Tim\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js

Replace all instances of 16777216 with 1677721600

This allows more memory to be used and large trees to be generated

**Comment by JetSetDoritos** [comment]
When I edit the vis.js file and use Notepad++ find and replace all function to replace 16777216 with 1677721600 I am able to generate large trees, 150+ node trees in my case.

**Comment by AtaTrkgl** [comment]
Have you managed to fix this problem?

**Comment by vorburger** [comment]
I think this issue IS a duplicate of #6, and the simplest solution (to me) seems to me not to bother about tweaking vis.js memory settings, but simply to [generate only the dot file with kingraph, and let Graphwiz produce the SVG and PDF](https://github.com/rstacruz/kingraph/issues/6#issuecomment-417332949). I have recommended this [in the README of my fork](https://github.com/vorburger/kingraph/commit/80f37bd198516bac6aeb47f985b7bb9cc128f4e6).
