### ISSUE TITLE
Issue with very large families 

### ISSUE THREAD

**Issue by Tb8854** [rstacruz/kingraph#6]
Hello, 

When I go for a large family (which works in smaller chunks) I have the following error 

When I run the following 

`kingraph myfamily_all.yml -F png > myfamily_all.png`

I get the following result. 

```
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:5:20800)
    at stackTrace (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:5:20983)
    at abort (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:28:5424)
    at abortOnCannotGrowMemory (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:5:21343)
    at enlargeMemory (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:5:21788)
    at Function.dynamicAlloc [as alloc] (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:5:6269)
    at _sbrk (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:5:602676)
    at N4 (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:21:7406)
    at cK (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:13:185312)
    at bK (/usr/local/lib/node_modules/kingraph/node_modules/viz.js/viz.js:13:185061)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

Adding options (1), (2) or (3) has no effect. The family isn't _that_ big - around 200 lines and 400-500 people in 10 houses. 

Any advice appreciated. 

Mac OS 10.13.3

**Comment by vsmalladi** [comment]
I also have this issue.

**Comment by janisz** [comment]
It looks like it's a problem with viz.js. Temporary workaround is to use dot

```kingraph family.yaml --format=dot > family.dot  && dot -Tsvg family.dot > family.svg
```

**Comment by rstacruz** [comment]
Thanks for the help debugging the issue!

**Comment by rstacruz** [comment]
This seems to be worth at least documenting somewhere. Let's see if updating viz.js would help too.

**Comment by vinter-man** [comment]
for windows, if installed globally 

`npm list -g`
>>> 
```
C:\Users\user\AppData\Roaming\npm
└── kingraph@0.1.0
```

then open
`C:\Users\user\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js`

and replace `16777216 ` to, as example, `1677721600`
